[build]
  command = "npm run build"
  publish = "dist"

# Variables de entorno para producción
[build.environment]
  VITE_API_URL = "https://mybeats-api.mybeats.workers.dev/api"
  VITE_R2_PUBLIC_URL = "https://pub-089c50aada404ece8b78efd1892e21d1.r2.dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
